import LayoutApp from "@/components/layout";
import queryClient from "@/hooks/queryClient";
import "@/styles/globals.css";
import type { AppProps } from "next/app";
import { QueryClientProvider } from "@tanstack/react-query";
import Head from "next/head";
function HeadMeta() {
  return (
    <Head>
      <link
        href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:wght@500&display=swap"
        rel="stylesheet"
      />
    </Head>
  );
}
export default function App({ Component, pageProps }: AppProps) {


  return (
    <QueryClientProvider client={queryClient}>
      <LayoutApp>
        <Head>
          <title>weatherapp</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link
            rel="preconnect"
            href="https://fonts.gstatic.com"
            crossOrigin=""
          />
        </Head>
        <HeadMeta />
        <Component {...pageProps} />
      </LayoutApp>
    </QueryClientProvider>
  );
}
